import { Platform, StatusBar as NativeStatusBar, StyleSheet } from "react-native";
import { DESIGN } from "./design";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DESIGN.colors.background },
  hero: { height: "48%", backgroundColor: DESIGN.colors.primarySoft },
  heroImage: { width: "100%", height: "100%" },
  heroFallback: { flex: 1, alignItems: "center", justifyContent: "center" },
  heroEmoji: { fontSize: 90 },
  welcomeBody: { flex: 1, padding: 26, alignItems: "center" },
  brand: { fontSize: 42, fontWeight: "800", marginTop: 5, color: DESIGN.colors.textPrimary },
  tagline: { fontSize: 16, color: DESIGN.colors.textSecondary, marginTop: 8, marginBottom: 28, textAlign: "center" },
  introScroll: { paddingBottom: 24, backgroundColor: DESIGN.colors.background },
  introHero: { height: 300, backgroundColor: DESIGN.colors.primarySoft },
  introPanel: {
    marginTop: -24,
    padding: 22,
    paddingTop: 28,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: DESIGN.colors.surface,
  },
  introClaim: { color: DESIGN.colors.textPrimary, fontSize: 30, lineHeight: 36, fontWeight: "800", textAlign: "center", marginBottom: 24 },
  benefitRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  benefitItem: { width: "31%", alignItems: "center", paddingVertical: 12, borderRadius: 16, backgroundColor: DESIGN.colors.background },
  benefitIcon: { color: DESIGN.colors.primary, fontSize: 22, fontWeight: "800", marginBottom: 6 },
  benefitText: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 16, fontWeight: "700", textAlign: "center" },
  introTransport: { minHeight: 64, flexDirection: "row", alignItems: "center", paddingHorizontal: 18, borderRadius: 19, backgroundColor: DESIGN.colors.textPrimary, shadowColor: DESIGN.colors.textPrimary, shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  transportText: { flex: 1, color: DESIGN.colors.surface, fontSize: 18, fontWeight: "700" },
  introServiceRow: { minHeight: 62, flexDirection: "row", alignItems: "center", marginTop: 12, paddingHorizontal: 18, borderWidth: 1, borderColor: "#dce3ea", borderRadius: 19, backgroundColor: DESIGN.colors.surface },
  serviceIcon: { width: 34, fontSize: 22, textAlign: "left" },
  serviceText: { flex: 1, color: DESIGN.colors.textPrimary, fontSize: 16, fontWeight: "700" },
  serviceArrow: { color: DESIGN.colors.textSecondary, fontSize: 28, lineHeight: 28 },
  introLogin: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", marginTop: 22 },
  introLoginText: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "700" },
  introSignup: { alignItems: "center", paddingVertical: 10 },
  introSignupText: { color: DESIGN.colors.primary, fontSize: 14, fontWeight: "700" },
  headerSafeArea: { backgroundColor: DESIGN.colors.surface, paddingTop: Platform.OS === "android" ? NativeStatusBar.currentHeight || 0 : 0 },
  header: { paddingHorizontal: DESIGN.spacing.xl, paddingTop: DESIGN.spacing.md, paddingBottom: DESIGN.spacing.md, flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: DESIGN.colors.surface, borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border },
  headerCompact: { paddingHorizontal: DESIGN.spacing.xl, paddingVertical: DESIGN.spacing.sm, flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "transparent", borderBottomWidth: 0 },
  logo: { fontSize: 12, fontWeight: "800", color: DESIGN.colors.primary, letterSpacing: 1.6 },
  headerTitle: { color: DESIGN.colors.textPrimary, fontSize: 24, fontWeight: "800", marginTop: DESIGN.spacing.xs },
  headerIconButton: { width: 32, height: 32, borderRadius: DESIGN.radius.medium, borderWidth: 1, borderColor: DESIGN.colors.border, alignItems: "center", justifyContent: "center", backgroundColor: DESIGN.colors.surface },
  headerSignOut: { color: DESIGN.colors.textSecondary, fontWeight: "800", fontSize: 15 },
  form: { padding: DESIGN.spacing.xxl, gap: DESIGN.spacing.md },

  formBackHeader: { flexDirection: "row", alignItems: "center", gap: DESIGN.spacing.md, paddingHorizontal: DESIGN.spacing.xl, paddingBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border },
  formBackButton: { minHeight: 44, minWidth: 82, justifyContent: "center" },
  formBackButtonInline: { minHeight: 44, alignSelf: "flex-start", justifyContent: "center", marginBottom: DESIGN.spacing.md },
  formBackText: { color: DESIGN.colors.primary, fontSize: 15, fontWeight: "800" },
  formBackTitle: { flex: 1, color: DESIGN.colors.textPrimary, fontSize: 19, fontWeight: "800" },
  formIntroTitle: { color: DESIGN.colors.textPrimary, fontSize: 26, fontWeight: "800", marginBottom: DESIGN.spacing.xs },
  formIntroText: { color: DESIGN.colors.textSecondary, fontSize: 14, lineHeight: 20, marginBottom: DESIGN.spacing.lg },
  formSectionCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 18, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.03, shadowRadius: 7, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  formSectionTitle: { color: DESIGN.colors.textPrimary, fontSize: 16, fontWeight: "800", marginBottom: DESIGN.spacing.md },
  fieldError: { color: DESIGN.colors.danger, fontSize: 13, lineHeight: 18, marginTop: -2, marginBottom: DESIGN.spacing.sm },
  optionCard: { minHeight: 58, borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 14, paddingHorizontal: DESIGN.spacing.md, paddingVertical: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.sm, backgroundColor: DESIGN.colors.surface },
  optionCardActive: { borderColor: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primarySoft },
  optionTitle: { color: DESIGN.colors.textPrimary, fontSize: 14, fontWeight: "800", marginBottom: 3 },
  optionTitleActive: { color: DESIGN.colors.primary },
  optionDescription: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 17 },
  optionDescriptionActive: { color: DESIGN.colors.textPrimary },
  reviewRow: { borderTopWidth: 1, borderTopColor: DESIGN.colors.border, paddingVertical: DESIGN.spacing.sm },
  reviewLabel: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "700", marginBottom: 3 },
  reviewValue: { color: DESIGN.colors.textPrimary, fontSize: 14, lineHeight: 20, fontWeight: "600" },
  registrationContent: { padding: DESIGN.spacing.xxl, paddingBottom: 40 },
  content: { padding: DESIGN.spacing.xl, paddingBottom: 40 },
  requestContent: { padding: DESIGN.spacing.xl, paddingTop: DESIGN.spacing.md, paddingBottom: 40, backgroundColor: DESIGN.colors.background },
  stepHeader: { marginBottom: DESIGN.spacing.md },
  stepCounter: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "700", marginBottom: 4 },
  stepTitle: { color: DESIGN.colors.textPrimary, fontSize: 26, fontWeight: "800" },
  stepRule: { height: 2, width: 76, borderRadius: 2, backgroundColor: DESIGN.colors.primary, marginTop: DESIGN.spacing.md },
  requestProgressLine: { flexDirection: "row", gap: 6, marginBottom: DESIGN.spacing.xl },
  requestProgressSegment: { flex: 1, height: 3, borderRadius: 3, backgroundColor: DESIGN.colors.border },
  requestProgressSegmentActive: { backgroundColor: DESIGN.colors.primary },
  requestProgress: { flexDirection: "row", justifyContent: "space-between", marginBottom: DESIGN.spacing.lg },
  requestProgressItem: { flex: 1, alignItems: "center" },
  requestProgressDot: { width: 28, height: 28, borderRadius: DESIGN.radius.large, borderWidth: 1, borderColor: DESIGN.colors.border, alignItems: "center", justifyContent: "center", backgroundColor: DESIGN.colors.surface },
  requestProgressDotActive: { backgroundColor: DESIGN.colors.primary, borderColor: DESIGN.colors.primary },
  requestProgressNumber: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "800" },
  requestProgressNumberActive: { color: DESIGN.colors.surface },
  requestProgressLabel: { color: DESIGN.colors.textSecondary, fontSize: 11, fontWeight: "700", marginTop: DESIGN.spacing.xs, textAlign: "center" },
  requestProgressLabelActive: { color: DESIGN.colors.textPrimary },
  requestPanel: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, backgroundColor: DESIGN.colors.surface },
  requestPanelFlat: { borderTopWidth: 1, borderTopColor: DESIGN.colors.border, paddingTop: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.lg },
  formSectionLabel: { color: DESIGN.colors.textPrimary, fontSize: 13, fontWeight: "800", marginBottom: DESIGN.spacing.sm, marginTop: DESIGN.spacing.md },
  chipGrid: { flexDirection: "row", flexWrap: "wrap", gap: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.md },
  selectChip: { minHeight: 44, borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, paddingHorizontal: DESIGN.spacing.md, paddingVertical: 9, justifyContent: "center", backgroundColor: DESIGN.colors.surface },
  selectChipActive: { borderColor: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primary },
  selectChipText: { color: DESIGN.colors.textPrimary, fontSize: 13, fontWeight: "600" },
  selectChipTextActive: { color: DESIGN.colors.surface },
  compactInput: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, paddingHorizontal: DESIGN.spacing.md, paddingVertical: 10, fontSize: 14, color: DESIGN.colors.textPrimary, backgroundColor: DESIGN.colors.surface, marginBottom: DESIGN.spacing.sm },
  inlineSecondary: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, paddingHorizontal: DESIGN.spacing.md, paddingVertical: 10, alignItems: "center", backgroundColor: DESIGN.colors.surface, marginBottom: DESIGN.spacing.sm },
  inlinePickerRow: { flexDirection: "row", gap: DESIGN.spacing.sm, marginTop: DESIGN.spacing.sm },
  inlinePicker: { flex: 1 },
  requestHint: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 18, marginTop: DESIGN.spacing.md },
  requestNavRow: { flexDirection: "row", gap: 10, marginTop: 2 },
  requestNavRowSplit: { flexDirection: "row", gap: DESIGN.spacing.md, marginTop: DESIGN.spacing.md },
  requestNavButton: { flex: 1 },
  pricePrincipleBox: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, padding: DESIGN.spacing.lg, marginTop: DESIGN.spacing.lg, backgroundColor: DESIGN.colors.background },
  pricePrincipleTitle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "800" },
  summaryLabel: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginTop: DESIGN.spacing.lg },
  summaryValue: { color: DESIGN.colors.textPrimary, fontSize: 15, lineHeight: 21, marginTop: 4 },
  summaryLine: { borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border, paddingBottom: DESIGN.spacing.md, marginBottom: DESIGN.spacing.sm },
  requestSuccessContent: { flex: 1, padding: 28, alignItems: "center", justifyContent: "center", backgroundColor: DESIGN.colors.background },
  successMark: { width: 56, height: 56, borderRadius: 28, overflow: "hidden", backgroundColor: DESIGN.colors.textPrimary, color: DESIGN.colors.surface, fontSize: 34, lineHeight: 54, textAlign: "center", marginBottom: 18 },
  requestDetailContent: { padding: DESIGN.spacing.xl, paddingTop: DESIGN.spacing.md, paddingBottom: 40, backgroundColor: DESIGN.colors.background },
  detailStatusTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: DESIGN.spacing.md, marginBottom: DESIGN.spacing.sm },
  detailEyebrow: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase" },
  detailStatusPill: { alignSelf: "flex-start", maxWidth: "48%", color: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primarySoft, borderRadius: 999, overflow: "hidden", paddingHorizontal: 9, paddingVertical: 5, fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
  detailSectionTitleV2: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "800", marginBottom: DESIGN.spacing.md },
  detailSectionHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.sm },
  detailBodyText: { color: DESIGN.colors.textPrimary, fontSize: 14, lineHeight: 21 },
  detailBodyMuted: { color: DESIGN.colors.textSecondary, fontSize: 14, lineHeight: 21 },
  detailPriceText: { color: DESIGN.colors.textPrimary, fontSize: 24, lineHeight: 30, fontWeight: "800", marginBottom: DESIGN.spacing.sm },
  detailProviderName: { color: DESIGN.colors.textPrimary, fontSize: 17, lineHeight: 23, fontWeight: "800", marginBottom: DESIGN.spacing.xs },
  detailOfferCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  detailOfferAccepted: { borderColor: DESIGN.colors.success, backgroundColor: "#F0FDF4" },
  detailOfferRejected: { opacity: 0.72 },
  detailOfferMessage: { color: DESIGN.colors.textPrimary, fontSize: 14, lineHeight: 21, marginTop: DESIGN.spacing.sm, paddingTop: DESIGN.spacing.sm, borderTopWidth: 1, borderTopColor: DESIGN.colors.border },
  detailRefreshButton: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 12, paddingHorizontal: DESIGN.spacing.md, paddingVertical: 8, backgroundColor: DESIGN.colors.surface },
  detailRefreshText: { color: DESIGN.colors.primary, fontSize: 12, fontWeight: "800" },
  detailEmptyCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  detailEmptyTitle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "800" },
  detailEmptyText: { color: DESIGN.colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 4 },
  detailDangerZone: { borderWidth: 1, borderColor: "#F8CACA", borderRadius: 16, padding: DESIGN.spacing.lg, marginTop: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.md, backgroundColor: "#FFF7F7" },
  detailDangerTitle: { color: DESIGN.colors.danger, fontSize: 15, fontWeight: "800" },
  detailDangerCopy: { color: DESIGN.colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 4 },
  detailTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border, paddingBottom: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.lg },
  detailHeroTitle: { color: DESIGN.colors.textPrimary, fontSize: 24, fontWeight: "800", lineHeight: 30 },
  detailSectionFlat: { borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border, paddingBottom: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.lg },
  detailTwoColumnRow: { flexDirection: "row", gap: DESIGN.spacing.md, marginBottom: DESIGN.spacing.lg },
  detailMiniSection: { flex: 1, borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border, paddingBottom: DESIGN.spacing.md },
  detailValueStrong: { color: DESIGN.colors.textPrimary, fontSize: 14, fontWeight: "700", lineHeight: 20 },
  routeEndpoint: { color: DESIGN.colors.textPrimary, fontSize: 17, fontWeight: "700", lineHeight: 23 },
  routeArrowDown: { color: DESIGN.colors.textSecondary, fontSize: 18, marginVertical: DESIGN.spacing.xs },
  offerHeaderStrip: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.sm },
  offerRowCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, padding: DESIGN.spacing.md, marginBottom: DESIGN.spacing.sm, backgroundColor: DESIGN.colors.surface },
  requestDetailHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  requestDetailStatus: { color: DESIGN.colors.textPrimary, fontSize: 13, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, backgroundColor: DESIGN.colors.primarySoft, overflow: "hidden" },
  detailSectionCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, padding: 14, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.03, shadowRadius: 5, shadowOffset: { width: 0, height: 1 }, elevation: 1 },
  detailSectionTitle: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginBottom: 8 },
  detailPrimary: { color: DESIGN.colors.textPrimary, fontSize: 18, fontWeight: "800" },
  detailLabel: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "800", marginTop: 8 },
  detailValue: { color: DESIGN.colors.textPrimary, fontSize: 14, lineHeight: 20, marginTop: 3 },
  transportLead: { marginTop: -DESIGN.spacing.sm, marginBottom: DESIGN.spacing.lg },
  detailMuted: { color: DESIGN.colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 4 },
  offerCardCompact: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, padding: 14, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.04, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  offerPriceCompact: { color: DESIGN.colors.textPrimary, fontSize: 17, fontWeight: "800", marginBottom: 4 },
  appContent: { padding: DESIGN.spacing.xl, paddingTop: DESIGN.spacing.lg, paddingBottom: 96, backgroundColor: DESIGN.colors.background },
  shellEyebrow: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1.1, marginBottom: DESIGN.spacing.sm },
  dashboardPanel: { gap: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.lg },
  dashboardHeaderRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: DESIGN.spacing.md },
  dashboardHeader: { flex: 1 },
  dashboardTitle: { color: DESIGN.colors.textPrimary, fontSize: 26, fontWeight: "800", lineHeight: 32 },
  dashboardSubtitle: { color: DESIGN.colors.textSecondary, fontSize: 14, lineHeight: 20, marginTop: DESIGN.spacing.xs },
  roleChip: { color: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primarySoft, borderRadius: 999, overflow: "hidden", paddingHorizontal: 10, paddingVertical: 5, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  actionRowPrimary: { minHeight: 72, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: DESIGN.colors.actionBlue, borderRadius: DESIGN.radius.large, paddingHorizontal: DESIGN.spacing.md, paddingVertical: DESIGN.spacing.md, backgroundColor: DESIGN.colors.actionBlue, shadowColor: DESIGN.colors.actionBlue, shadowOpacity: 0.18, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  actionIconPrimary: { width: 36, height: 36, borderRadius: 12, overflow: "hidden", backgroundColor: "rgba(255,255,255,0.18)", color: DESIGN.colors.surface, fontSize: 18, lineHeight: 34, textAlign: "center", marginRight: DESIGN.spacing.md, fontWeight: "800" },
  actionTitlePrimary: { color: DESIGN.colors.surface, fontSize: 15, fontWeight: "700" },
  actionSubtitlePrimary: { color: "rgba(255,255,255,0.78)", fontSize: 13, marginTop: 3 },
  actionChevronPrimary: { color: "rgba(255,255,255,0.78)", fontSize: 24, lineHeight: 24, marginLeft: DESIGN.spacing.sm },
  transportPageHeader: { marginBottom: DESIGN.spacing.md },
  transportPageTitle: { color: DESIGN.colors.textPrimary, fontSize: 26, fontWeight: "800", lineHeight: 32 },
  transportPageSubtitle: { color: DESIGN.colors.textSecondary, fontSize: 14, lineHeight: 20, marginTop: DESIGN.spacing.xs },
  activeFiltersRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: DESIGN.spacing.xs, marginTop: DESIGN.spacing.sm },
  activeFilterChip: { alignSelf: "flex-start", backgroundColor: DESIGN.colors.primarySoft, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, overflow: "hidden" },
  activeFilterChipText: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800" },
  actionRow: { minHeight: 72, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, paddingHorizontal: DESIGN.spacing.md, paddingVertical: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.03, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  actionIcon: { width: 36, height: 36, borderRadius: 12, overflow: "hidden", backgroundColor: DESIGN.colors.background, color: DESIGN.colors.primary, fontSize: 18, lineHeight: 34, textAlign: "center", marginRight: DESIGN.spacing.md, fontWeight: "800" },
  actionBody: { flex: 1 },
  actionSubtitle: { color: DESIGN.colors.textSecondary, fontSize: 13, marginTop: 3 },
  actionChevron: { color: DESIGN.colors.textSecondary, fontSize: 24, lineHeight: 24, marginLeft: DESIGN.spacing.sm },
  dashboardSection: { marginTop: DESIGN.spacing.lg },
  sectionLabel: { color: DESIGN.colors.textSecondary, fontSize: 11, fontWeight: "800", letterSpacing: 1, marginBottom: DESIGN.spacing.sm, textTransform: "uppercase" },
  emptyPanel: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, backgroundColor: DESIGN.colors.surface },
  emptyPanelCompact: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  emptyTitle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "700" },
  emptyCopy: { color: DESIGN.colors.textSecondary, fontSize: 13, lineHeight: 18, marginTop: 4 },
  dispatchRow: { flexDirection: "row", alignItems: "center", gap: DESIGN.spacing.md, borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  dispatchMain: { flex: 1 },
  actionCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, marginTop: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.04, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  actionTitle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "700" },
  transportSectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: DESIGN.spacing.md, marginBottom: DESIGN.spacing.sm },
  transportFilterHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: DESIGN.spacing.sm },
  filterToggleButton: { flexDirection: "row", alignItems: "center", gap: DESIGN.spacing.sm, minHeight: 44, justifyContent: "center" },
  filterToggleChevron: { color: DESIGN.colors.textSecondary, fontSize: 11, fontWeight: "800" },
  filterFields: { gap: DESIGN.spacing.sm, marginTop: DESIGN.spacing.sm },
  transportCount: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "800" },
  segmentedBar: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: DESIGN.colors.border, marginBottom: DESIGN.spacing.lg },
  segmentedItem: { paddingRight: DESIGN.spacing.lg, paddingVertical: DESIGN.spacing.md, minHeight: 44, justifyContent: "center", alignItems: "flex-start" },
  segmentedText: { color: DESIGN.colors.textSecondary, fontSize: 13, fontWeight: "600" },
  segmentedTextActive: { color: DESIGN.colors.textPrimary, fontWeight: "800" },
  segmentedUnderline: { height: 2, width: "100%", backgroundColor: DESIGN.colors.primary, marginTop: DESIGN.spacing.sm, borderRadius: 2 },
  dispatchCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, paddingHorizontal: DESIGN.spacing.md, paddingVertical: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.sm, backgroundColor: DESIGN.colors.surface },
  dispatchHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4 },
  dispatchLabel: { color: DESIGN.colors.textSecondary, fontSize: 10, fontWeight: "800", letterSpacing: 0.9 },
  dispatchVehicle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "700", marginBottom: 2 },
  dispatchRoute: { color: DESIGN.colors.textPrimary, fontSize: 14, fontWeight: "700" },
  routeLine: { color: DESIGN.colors.textPrimary, fontSize: 14, lineHeight: 19, marginTop: 4 },
  dispatchFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", marginTop: DESIGN.spacing.sm },
  dispatchMeta: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 17 },
  dispatchArrow: { color: DESIGN.colors.textSecondary, fontSize: 19, fontWeight: "700" },
  statusPill: { alignSelf: "flex-start", color: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primarySoft, borderRadius: 999, overflow: "hidden", paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
  transportCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, padding: 14, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface, shadowColor: DESIGN.colors.primaryDark, shadowOpacity: 0.04, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  transportCardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  transportCardMain: { flex: 1 },
  transportEyebrow: { color: DESIGN.colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginBottom: 3 },
  transportTitle: { color: DESIGN.colors.textPrimary, fontSize: 17, fontWeight: "800" },
  transportProblem: { color: "#334155", fontSize: 13, marginTop: 2 },
  transportRoute: { color: "#334155", fontSize: 13, marginTop: 8, lineHeight: 18 },
  transportMetaRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  transportMeta: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "700" },
  transportBadge: { color: DESIGN.colors.textPrimary, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  transportStatus: { color: DESIGN.colors.textPrimary, fontSize: 12, fontWeight: "800" },
  transportOfferCount: { color: DESIGN.colors.primary, fontSize: 12, fontWeight: "800", marginTop: 8, textTransform: "uppercase" },
  transportArrow: { color: DESIGN.colors.textSecondary, fontSize: 20, fontWeight: "800" },
  bottomNavSafeArea: { backgroundColor: DESIGN.colors.surface, paddingBottom: 10 },
  bottomNav: { minHeight: 80, flexDirection: "row", alignItems: "center", justifyContent: "space-around", borderTopWidth: 1, borderTopColor: DESIGN.colors.border, paddingTop: 8, paddingBottom: 10, backgroundColor: DESIGN.colors.surface },
  bottomNavItem: { flex: 1, minHeight: 56, alignItems: "center", justifyContent: "center", gap: 4 },
  bottomNavIcon: { color: DESIGN.colors.textSecondary, fontSize: 23, lineHeight: 27, fontWeight: "700" },
  bottomNavText: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 16, fontWeight: "600" },
  bottomNavTextActive: { color: DESIGN.colors.primary },
  bottomNavPlusCircle: { width: 48, height: 48, borderRadius: 24, overflow: "hidden", backgroundColor: DESIGN.colors.actionBlue, alignItems: "center", justifyContent: "center", marginTop: -16, shadowColor: DESIGN.colors.actionBlue, shadowOpacity: 0.3, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  bottomNavPlusGlyph: { color: DESIGN.colors.surface, fontSize: 28, lineHeight: 30, fontWeight: "700", marginTop: -3 },
  bottomNavCreateLabel: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 16, fontWeight: "600" },
  profileHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
  profileBack: { color: DESIGN.colors.textPrimary, fontSize: 16, fontWeight: "700" },
  profileHeaderIcon: { color: DESIGN.colors.primary, fontSize: 24 },
  profileCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: 18, marginBottom: 14, backgroundColor: DESIGN.colors.surface },
  profileName: { color: DESIGN.colors.textPrimary, fontSize: 24, fontWeight: "800" },
  profileRole: { color: DESIGN.colors.textSecondary, marginTop: 5, fontWeight: "700" },
  profileFieldLabel: { color: DESIGN.colors.textSecondary, fontSize: 12, fontWeight: "800", marginTop: 12 },
  profileFieldValue: { color: DESIGN.colors.textPrimary, fontSize: 16, marginTop: 3 },
  profileLinkCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: 16, marginBottom: 12, backgroundColor: DESIGN.colors.surface },
  profileLogoutRow: { borderWidth: 1, borderColor: "#F2D5D5", borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.md, marginTop: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.xl, backgroundColor: "#FFF7F7", alignItems: "center" },
  profileLogoutText: { color: DESIGN.colors.danger, fontSize: 14, fontWeight: "700" },
  profileLinkTitle: { color: DESIGN.colors.textPrimary, fontSize: 17, fontWeight: "800" },
  profileLinkText: { color: DESIGN.colors.textSecondary, marginTop: 5 },
  // Redesign profilu do karet: kompaktní stavové řádky a nadpisy karet.
  profileCardHeading: { color: DESIGN.colors.textPrimary, fontSize: 16, fontWeight: "800", marginBottom: 4 },
  profileSummaryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 7, borderTopWidth: 1, borderTopColor: DESIGN.colors.border },
  profileSummaryLabel: { color: DESIGN.colors.textSecondary, fontSize: 13, fontWeight: "700", flexShrink: 1 },
  profileSummaryValue: { color: DESIGN.colors.textPrimary, fontSize: 14, fontWeight: "600", textAlign: "right", flexShrink: 1, marginLeft: 12 },
  // Volitelné upřesnění přesného místa ve formulářích (nenápadná akce + vysvětlení).
  expandToggle: { alignSelf: "flex-start", minHeight: 44, justifyContent: "center", paddingHorizontal: 8, marginTop: 2, marginBottom: DESIGN.spacing.sm },
  expandToggleText: { color: DESIGN.colors.primary, fontSize: 13, fontWeight: "700" },
  privateHintText: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 18, marginBottom: DESIGN.spacing.sm },
  navigationSection: { marginTop: 10 },
  customerContent: { padding: 20, paddingTop: 18, paddingBottom: 32 },
  scroll: { flex: 1 },
  bigTitle: { fontSize: 24, fontWeight: "800", color: DESIGN.colors.textPrimary, marginBottom: DESIGN.spacing.sm },
  primary: { backgroundColor: DESIGN.colors.primary, borderRadius: DESIGN.radius.large, paddingVertical: DESIGN.spacing.md, paddingHorizontal: DESIGN.spacing.lg, alignItems: "center", marginTop: DESIGN.spacing.lg },
  primaryText: { color: DESIGN.colors.surface, fontSize: 14, fontWeight: "800", letterSpacing: 0.2 },
  secondary: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, paddingVertical: DESIGN.spacing.md, paddingHorizontal: DESIGN.spacing.lg, alignItems: "center", marginTop: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  secondaryText: { color: DESIGN.colors.textPrimary, fontWeight: "800", fontSize: 14 },
  link: { color: DESIGN.colors.primary, fontWeight: "700", marginTop: 18 },
  input: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.medium, paddingHorizontal: DESIGN.spacing.md, paddingVertical: DESIGN.spacing.md, fontSize: 15, color: DESIGN.colors.textPrimary, backgroundColor: DESIGN.colors.surface, marginTop: DESIGN.spacing.sm },
  roleCard: { flexDirection: "row", alignItems: "center", gap: 16, borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: 18, marginTop: 10 },
  roleIcon: { fontSize: 35 },
  roleTitle: { fontSize: 18, fontWeight: "800" },
  muted: { color: DESIGN.colors.textSecondary, marginTop: 3 },
  mapWrap: { height: 280, marginHorizontal: 14, borderRadius: 18, overflow: "hidden", position: "relative" },
  customerMapWrap: {
    height: 230,
    borderRadius: 24,
    shadowColor: DESIGN.colors.textPrimary,
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  map: { flex: 1 },
  locationButton: { position: "absolute", right: 12, top: 12, backgroundColor: DESIGN.colors.surface, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12 },
  customerLocationButton: {
    right: 12,
    top: 12,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 18,
    shadowColor: DESIGN.colors.textPrimary,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  locationButtonText: { fontWeight: "700", color: DESIGN.colors.textPrimary },
  driverTop: { paddingHorizontal: 20, paddingBottom: 8 },
  list: { padding: 20, paddingTop: 8 },
  filterRow: { gap: 8, paddingRight: 12 },
  filterPanel: { backgroundColor: DESIGN.colors.background, borderRadius: 14, padding: 8, marginTop: 8 },
  resultCount: { color: DESIGN.colors.textSecondary, fontWeight: "700", marginTop: 14, marginBottom: 4 },
  sectionTitle: { fontSize: 16, fontWeight: "800", color: DESIGN.colors.textPrimary, marginBottom: DESIGN.spacing.sm },
  jobCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  marketCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: DESIGN.colors.surface },
  acceptedCard: { borderWidth: 1, borderColor: DESIGN.colors.success, borderRadius: DESIGN.radius.large, padding: DESIGN.spacing.lg, marginBottom: DESIGN.spacing.md, backgroundColor: "#ecfdf5" },
  acceptedTitle: { color: DESIGN.colors.primary, fontSize: 12, fontWeight: "800", marginBottom: 4 },
  acceptedPrice: { color: DESIGN.colors.textPrimary, fontSize: 24, fontWeight: "800", marginTop: 12 },
  offerCard: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 16, padding: 16, marginBottom: 12, backgroundColor: DESIGN.colors.surface },
  offerTitle: { color: DESIGN.colors.textPrimary, fontSize: 15, fontWeight: "800" },
  offerPrice: { color: DESIGN.colors.textPrimary, fontSize: 24, fontWeight: "800", marginTop: 12 },
  offerEta: { color: DESIGN.colors.primary, fontSize: 16, fontWeight: "700", marginTop: 6 },
  offerMessage: { color: DESIGN.colors.textSecondary, marginTop: 10, fontStyle: "italic" },
  refreshButton: { borderWidth: 1, borderColor: DESIGN.colors.border, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 8, marginBottom: 10 },
  refreshButtonText: { color: DESIGN.colors.primary, fontWeight: "700" },
  marketEyebrow: { color: DESIGN.colors.primary, fontSize: 12, fontWeight: "800", letterSpacing: 0.5 },
  urgentBadge: { maxWidth: "58%", color: DESIGN.colors.primary, backgroundColor: DESIGN.colors.primarySoft, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, fontSize: 11, fontWeight: "800", textAlign: "right" },
  cardLabel: { color: DESIGN.colors.textPrimary, fontWeight: "800", marginTop: 12 },
  detailLink: { color: DESIGN.colors.primary, fontWeight: "800", textAlign: "right", marginTop: 14 },
  routesSection: { marginTop: 12, paddingTop: 18, borderTopWidth: 1, borderTopColor: DESIGN.colors.border },
  rowBetween: { flexDirection: "row", justifyContent: "space-between" },
  jobId: { fontWeight: "800" },
  badge: { fontSize: 11, fontWeight: "800", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: DESIGN.colors.primarySoft, color: DESIGN.colors.primary },
  jobTitle: { fontSize: 17, fontWeight: "700", marginTop: 10, marginBottom: 4 },
  empty: { color: DESIGN.colors.textSecondary, textAlign: "center", marginTop: 40 },
  bottomAction: { padding: 20 },
  label: { fontWeight: "800", marginTop: 14, color: DESIGN.colors.textPrimary },
  publicHintText: { color: DESIGN.colors.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 4, marginBottom: 6 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  chip: { borderWidth: 1, borderColor: DESIGN.colors.border, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 20 },
  chipActive: { backgroundColor: DESIGN.colors.primarySoft, borderColor: DESIGN.colors.primary },
  statusBox: { backgroundColor: DESIGN.colors.background, borderRadius: 14, padding: 16, marginTop: 16 },
  statusTitle: { fontSize: 17, fontWeight: "800", color: DESIGN.colors.textPrimary, marginBottom: 5 },
  error: { color: DESIGN.colors.danger, marginBottom: 10 },
  customerDescription: { color: DESIGN.colors.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 4, marginBottom: 8 },
  customerPrimary: {
    backgroundColor: DESIGN.colors.textPrimary,
    borderRadius: 18,
    minHeight: 60,
    paddingHorizontal: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    shadowColor: DESIGN.colors.textPrimary,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  customerActionRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#e3e8ef",
    borderRadius: 17,
    backgroundColor: DESIGN.colors.surface,
  },
  customerActionRowSubtle: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    paddingHorizontal: 16,
    borderRadius: 17,
  },
  customerActionIcon: { width: 28, color: DESIGN.colors.primary, fontSize: 20, fontWeight: "700" },
  customerActionText: { flex: 1, color: DESIGN.colors.textPrimary, fontSize: 16, fontWeight: "700" },
  customerActionTextSubtle: { flex: 1, color: DESIGN.colors.textSecondary, fontSize: 15, fontWeight: "600" },
  customerActionArrow: { color: DESIGN.colors.textSecondary, fontSize: 27, lineHeight: 27 },
  vehicleCard: {
    borderWidth: 1,
    borderColor: DESIGN.colors.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: DESIGN.colors.surface,
  },
  vehicleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  vehicleName: {
    fontSize: 18,
    fontWeight: "800",
    color: DESIGN.colors.textPrimary,
  },
  vehicleInfo: {
    fontSize: 14,
    color: DESIGN.colors.textSecondary,
    marginTop: 3,
  },
  statusBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    marginTop: 6,
  },
  activeBadge: {
    backgroundColor: "#dcfce7",
    borderColor: "#22c55e",
    borderWidth: 1,
  },
  inactiveBadge: {
    backgroundColor: "#fef3c7",
    borderColor: "#f59e0b",
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: DESIGN.colors.textSecondary,
  },
  vehicleDetails: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 14,
    marginBottom: 10,
  },
  vehicleDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  vehicleDetailLabel: {
    color: DESIGN.colors.textSecondary,
    fontSize: 14,
    flex: 1
  },
  vehicleDetailValue: {
    color: DESIGN.colors.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "right",
  },
  vehicleEquipment: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 14,
    marginBottom: 12,
  },
  equipmentLabel: {
    color: DESIGN.colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
  },
  equipmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  equipmentItem: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    color: DESIGN.colors.textSecondary,
  },
  equipmentChecked: {
    backgroundColor: DESIGN.colors.primarySoft,
    borderColor: DESIGN.colors.primary,
    color: DESIGN.colors.primary,
  },
  vehicleActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  dangerButton: {
    backgroundColor: "#fef2f2",
    borderColor: "#ef4444",
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    flex: 1,
    alignItems: "center",
  },
  dangerButtonText: {
    color: "#ef4444",
    fontSize: 14,
    fontWeight: "700",
  },
  multilineInput: {
    height: 80,
    textAlignVertical: "top",
  },
});
